version: '3'

networks:
  nmp:
    driver: bridge

services:
  mysql:
    image: 'mysql:5.7'
    container_name: mysql
    restart: always
    command: --init-file /data/application/init.sql
    volumes:
      - ./conf/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:rw
      - ./data/mysql:/var/lib/mysql/:rw
      - ./src/db.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Hong_Kong
    ports:
      - "3306:3306"
    networks:
      - nmp
  app:
    container_name: app
    build: .
    ports:
      - 80:80
    environment:
      DOCUMENT_ROOT: /var/www
    volumes:
      - ./src:/var/www
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - nmp
